### ISSUE TITLE
Missing validation error message on checkboxes validation

### ISSUE THREAD

**Issue by zhanang19** [nafiesl/FormField#7] opened 2020-05-21 04:48 UTC
## Actual
After submitting a form with invalid data, I don't get an error.

## Expected
Submitting a form with input as shown in the form below will show an error like `The selected data2.0 is invalid`

![image](https://user-images.githubusercontent.com/19884603/82523214-b20ddd80-9b55-11ea-8a17-8b4f3e4f273d.png)

## How to reproduce
```php
// form.blade.php
{!! FormField::checkboxes('data2', ['a' => 'Aaaa', 'b' => 'Beee', 'c' => 'Ceee']) !!}

// AdminController.php
$request->validate([
    'data2' => ['required', 'array'],
    'data2.*' => [Rule::in(['a'])],
]);
```

**Comment by nafiesl** [comment] 2020-05-21 05:52
@zhanang19 thanks for your report.

I found this issue as well 2 years ago #4. I have closed the issue since the bug is not coming from this package, but from the LaravelCollective package https://github.com/LaravelCollective/html/issues/578.

Are you using the latest version? On laravel 7.x?

**Comment by nafiesl** [comment] 2020-05-21 05:56
Oops, wait @zhanang19, looks like I have miss-understood your report.

You were reporting about the validation message which didn't shown on the page, right? Not about the missing selected value of the checkbox?

**Comment by zhanang19** [comment] 2020-05-21 06:08
Thanks for your very fast response. 

> @zhanang19 thanks for your report.
> 
> I found this issue as well 2 years ago #4. I have closed the issue since the bug is not coming from this package, but from the LaravelCollective package [LaravelCollective/html#578](https://github.com/LaravelCollective/html/issues/578).
> 
> Are you using the latest version? On laravel 7.x?

Yup, I am using the latest version of Laravel 7.x here.



> Oops, wait @zhanang19, looks like I have miss-understood your report.
> 
> You were reporting about the validation message which didn't shown on the page, right? Not about the missing selected value of the checkbox?

Yup, I already very confused for this issue. But, just want to say a good job for this awesome package :)

**Comment by nafiesl** [comment] 2020-05-21 13:31
Thank @zhanang19, I means a lot.

Ok, I have managed to reproduce our issue. The error should be shown below the checkboxes, but it didn't. I will try to figure out how to fix it.

![screen_20-05-21_009](https://user-images.githubusercontent.com/8721551/82563839-57eb3780-9baa-11ea-874a-0f6429697165.jpg)

**Comment by nafiesl** [comment] 2020-05-22 02:22
@zhanang19 the PR has been merged. Could you possible help once again with the `dev-master`?
```
$ composer require luthfi/formfield dev-master
```

I we have no issue, I will create a new release tag.

Thanks.

**Comment by zhanang19** [comment] 2020-05-22 09:45
> @zhanang19 the PR has been merged. Could you possible help once again with the `dev-master`?

I have tested it out using the master branch and it was work correctly. Thank you.

**Comment by nafiesl** [comment] 2020-05-22 13:54
Great, thanks for helping @zhanang19.

A new tag has been released https://github.com/nafiesl/FormField/releases/tag/2.1.1.

**Closed as completed by nafiesl** 2020-05-22 13:54 UTC
Labels: bug
